### ISSUE TITLE
No files created

### ISSUE THREAD

**Issue by Taiko3615** [borgand/inkscape_merge#3]
Hello, I am on osx, I have successfully installed inkscape_merge,

It seems to run file, I see in the log output that he is processing my file row by row,

But in the end no files are created.

After some reasearch I have foudn my mistake :-D

Actualyl the issue was the ouput path was wrong. By writing a fullpath for the ouput, it worked like a charm !

Hope this will help poeples in the future.

`inkscape_merge -f tag.svg -d codes.csv -o /Users/XXXXXX/Documents/XXXXXX/Certificate_Generator/test%d.pdf`

**Comment by borgand** [comment]
Thanks for the tip. I added a patch that should automatically turn output file to absolute path. Should fix this issue.
